### ISSUE TITLE
Protocol handler missing from URI posted by PoshBot

### ISSUE THREAD

**Issue by csandfeld** [poshbotio/PoshBot.Dilbert#1]
Dilbert comic is not shown because the returned URI does not include a ```http:``` or ```https:``` protocol handler. 

## Current Behavior
When invoking the ```!dilbert``` command, a URI without a protocol handler is posted, and no image is shown.

**Example:**
```//assets.amuniversal.com/8c92b0a0f6940136776e005056a9545d```

## Expected Behavior
When invoking the ```!dilbert``` command, a URI _with_ a protocol handler should be posted, and thus the image would be shown.

**Example:**
```http://assets.amuniversal.com/8c92b0a0f6940136776e005056a9545d```
... or ...
```https://assets.amuniversal.com/8c92b0a0f6940136776e005056a9545d```

## Possible Solution

Looks like the returned HTML source gives a URI without the protocol handler. Add protocol handler if it is missing. Alternatively use the links in the metadate for Twitter or Facebook Open Graph 

## Steps to Reproduce (for bugs)

1. Install PoshBot.Dilbert plugin
2. Invoke ```!dilbert```
3. Observe posted value

## Your Environment

Using Slack backend

* Module version used:
  * PoshBot 0.11.5
  * PoshBot.Dilbert 1.0.0
* Operating System and PowerShell version:
  * Windows 10 Enterprise Version 1809 (OS Build 17763.316)
  * PowerShell Version 5.1.17763.316

**Comment by devblackops** [comment]
@csandfeld Thanks for the heads up! Looks like the HTML source changed. I'll push a fix.

**Comment by devblackops** [comment]
Fixed in 5173ab10949c87d2f6144cc318ed7278921e2cb0

Version `1.1.0` released to [PowerShell Gallery](https://www.powershellgallery.com/packages/PoshBot.Dilbert/1.1.0).

**Comment by csandfeld** [comment]
Thanks :-)
